### PR TITLE
Adds WarcWriter class to project

### PR DESCRIPTION
**Pull request by acidus99**
This PR adds a `WarcWriter` class, which can create WARC files. It also supports per-record compression.

```
using(var warcWriter = new WarcWriter("example.warc.gz"))
{
    warchWriter.WriteRecord(warcInfoRecord);
    warchWriter.WriteRecord(requestRecord);
    warchWriter.WriteRecord(responseRecord);
}
```

This addition makes it pretty straightforward to write records to a WARC file and allows me to create WARCs in C#, which is great. This PR should be good to go as is. I'm open to any changes you suggest.

However several aspects of the current design of the abstract Record class and its implementations make it very painful to create records manually (e.g. `new RequestRecord(...)`) or via `RecordFactory`, which then you write to a WARC with `WarcWriter`:

* The only way to create a record is via its constructor. You cannot modify any properties after the fact. This means you have to know all the information ahead of time. This is annoying since I cannot iteratively add properties/data. There are also scenarios that are much harder to do such as when trying to add a `WARC-Concurrent-To` property to both a _request_ and _response_ record that point at each other since the IDs are created at different times.

* There is no common `BlockBytes` property on a record. The record propery you use to get the block bytes varies by record type, which complicates code.

* I can't control what WARC headers are created for a record. `WARC-Block-Digest` and `WARC-Payload-Digest` are both optional, but I can't not have them. The current design intermixes digest hash creation and payload hash creation record creation.

Ideally, the Records should just be plain old CLR objects, with each property with `public get; public set;`. This would allow me to decide and iteratively build the properties/headers that I want:

```
var record = new RequestRecord(); // Warc-Record-ID automatically generated if not passed via a constructor

record.IPAddress = "333.333.333.333";
record.BlockBytes = data; //also automatically sets the ContentLength property, which would be `private set;` only
record.TargetUri = targetUri;
```

The WARC parser would just populates those properties as well, and could have extra metadata such as whether a block digest checksum matches or not.

Payload detection/digest computing should be pulled out of record creation, so that they can be done by the parser, or when creating records ad-hoc, if the user wants it. Something like:

```
IPayloadDetector payloadDetector = new HttpPayloadDetector();
payloadDetector.ParseForPayload(record.BlockBytes);
if(payloadDetector.FoundPayload)
{
    // we detected a payload in the block, such as an HTTP response, so allow the user to populate those properties if they want
    record.PayloadBytes = payloadDetector.PayloadBytes
    record.PayloadContentType = payloadDetector.ContentType;
}
```

This approach makes it much easier to create WARC records iteratively. I plan to do this work for myself, but didn't want to include it here and make a crazy complex PR.

Would you be open to such as change to the way Records can be created and having their properties modified?

### CODE REVIEW

**Comment by nurhafiz** [comment]
I appreciate the interest, effort and suggestions.

1) I'm not a fan of having setters for fields that are meant to be initialized once. As such, I'm unable to accept that suggestion. However, something like `AddConcurrentTo(...)` can be added to accommodate the scenario that you brought up - adding `WARC-Concurrent-To`.

2) There is no common `BlockBytes `property because, as you know, not all record types have payloads. The design is to avoid having any conditional checks in the parser. If I'm not wrong, your suggestion of pulling the payload detection / digest computing out of the record creation and into the parser would mean that the parser has to be amended if a new custom or official record type is introduced.

3) You're right about not being able to opt-out of optional `WARC-Block-Digest` and `WARC-Payload-Digest`. Thanks for catching the bug.

As I do not have the time to fix no (3), and am reluctant to accommodate (1) and (2), perhaps it's best if you make your own fork instead?

Please accept my apologies.

**Comment by acidus99** [comment]
No need for apologies at all! Thank you for your hard work creating this.

To be clear, this discussion about changing the Record setters/hierarchy is totally unrelated to PR #2 , that adds a single class `WarcWriter` that writes your existing records to a file. I hope you accept this PR regardless of any other ideas I have, or forks that I do.

**Comment by nurhafiz** [comment]
Oops. Could you add in a corresponding test for your class and add a section in the README on how to call your method? I'll accept the PR then.

**Comment by acidus99** [comment]
sure

**Review by nurhafiz — CHANGES_REQUESTED** [review]
Could you add in a corresponding test for your class and add a section in the README on how to call your method?

Also, though 100% code coverage is not a good metric, I'd appreciate it f it is achieved.

**Comment by acidus99** [comment]
@nurhafiz I added XUnit tests for `WarcWriter` and the README.md with some examples. 

The WarcWriter tests read each WARC 1.1 test file, parses out the records, writes those records into temporary output WARC files, and then validates the output WARC files. It tests writing both uncompressed and per-record compression WARC output files. 

To validate the accuracy of the records in the output WARCs I changed the access modifier on 3 methods in `WarcParserTest` from `private` to `internal`. Specifically I did this for `TestFile()` `CreateTempFile()` and `DeleteFile()` because I use call those methods from `WarcWriterTest.` This avoids a lot of headache and to DRY the code so I don't have to duplicate the validation logic that `WarcParserTest` uses.

It might make sense to move these and other methods to a common `WarcTest` class which validates WARC Records and is used by both `WarcParserTest` and `WarcWriterTest`. That would also make it much easier for the WarcWriter tests to also validate against the new optional Payload and block digest changes you made. However that was a larger change that I didn't want to bundle into this PR unnecessarily. Do whatever your think is best.

**Comment by nurhafiz** [comment]
Thanks for the contribution. It may take a while for me to review them. 

Alternatively, seeing that you're passionate about making this library better, I would like to add you as a collaborator if you're interested. That way it'll be easier for you to make the recommended changes (except code styling e.g. setters over constructors :-)) yourself.

Let me know if you're keen. Otherwise, do wait for my review.

**Comment by acidus99** [comment]
Thanks for the offer. I'm doing a lot of crawling work recently, primarily non-HTTP stuff and decided to use WARC as my data-at-rest format, before ingesting it into other systems (an archive, a search engine index, etc). No need to be a collaborator yet. Let's get a few PRs under the belt and see how you feel. I have a PR for that solves issue #4 , but will wait for this PR to be reviewed before submitting.

**Pull request merged**
